### ISSUE TITLE
MissingOutputException in rule scale_scAbsolute

### ISSUE THREAD

**Issue by annahyan** [markowetzlab/scDNAseq-workflow#24]
Hi,

I have a few hundred cells and when I run the pipeline for all, it only completes for a handful and for all the others it throws an error like this:

`MissingOutputException in rule scale_scAbsolute in file /path/to/scDNAseq-workflow/workflow/rules/scale_scAbsolute.smk, line 1: 
Job 142  completed successfully, but some output files are missing. Missing files after 300 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:                   
results/500/smp/smp_cellX.rds`

I have already increased the latency time quite a bit (initially it was suggesting to set to 15), but it didn't solve the problem.

Could you please help me with this?

Thanks

**Comment by leachim** [comment]
Can you identify some of the files that fail? For example, just run it for a subset of cells until you have one or two example cells where it fails. Have you made sure to read all the info in the FAQ and made sure that your input conforms to our requirements? Have you tested the pipeline on our example cells? Snakemake will usually create log files that document the errors for the commands. I would need one of those to help you. This is just a very generic error message.
