### ISSUE TITLE
No text editors installed in the scAbsolute image

### ISSUE THREAD

**Issue by TBradley27** [markowetzlab/scDNAseq-workflow#26]
Hello,

In the current scDNAseq-workflow, both scAbsolute and scUnique are implemented as containers spawned from images hosted remotely.

To make it easier for users to modify and use the images, one option is for users to shell into the image, mount/bind relevant data and scripts, and then execute within this shell session. This can be used for generating copy number plots for example

However, for the current implementation, this is difficult as the image has none of the common CLI text editors installed (_e.g._ vim, nano, emacs _etc._). This makes it very difficult to modify the source code, and limits the flexibility of use of scAbsolute

**Comment by leachim** [comment]
you can just mount an updated scAbsolute folder in the container, that gives you access to text editing or run singularity containers, again that would give you access to the underlying file system

**Comment by TBradley27** [comment]
I can access the underlying the file system with the container, that is not the issue. The problem is that I can't edit the files at all once I am in the container.

Yeah, I already had to do the mount to get my modifications to work.
