### ISSUE TITLE
pseudodiploid/haploid cells as output

### ISSUE THREAD

**Issue by Urja25** [markowetzlab/scDNAseq-workflow#27]
Hi,

When I ran scAbsolute with the default ploidy window I noticed that a lot of cells (~50%) had copy number of 1 across the genome, which is not something we expect to see in the samples (blood cells, should be mainly diploid).
Therefore, I adjusted the ploidy window to be between 1.2-2.9 and this resulted in a much lower proportion of cells with CN across the genome as 1, yet, about 10-15% of such "haploid-looking" cells remain. I am wondering why this must be the case since the rpc values are good and reads in the cell are also sufficient for CN calling.
At first, I noticed this with just my sample, however, we are observing the same phenomenon in fibroblasts for example. A bit strange since we dont see this when running HMMCopy.

Thanks a lot!

**Comment by leachim** [comment]
Hey, that does seem a bit odd. In the first place, I'd always run scAbsolute with the default setting of minPloidy at 1.1 or 1.2, as it's set by default. The reason is that you wouldn't typically see cells with a ploidy of 1, as they shouldn't survive with so many genome losses, and the pipeline selects the minimum ploidy by default - if you set it to one and it is a truly diploid cell (without X chromosome) it will predict a ploidy of one which is obviously wrong. If you have samples from a female, it also sometimes helps to include the X chromosome for ploidy estimations (but copy number calls on the X chromosome tend to be less reliable). 
For the remaining haploid looking cells, can you send a screenshot or describe a bit more in detail what they look like? scAbsolute shouldn't call anything with a ploidy less than the minimum ploidy, so I assume the predicted ploidy is somewhere between 1 and 2?

**Comment by Urja25** [comment]
Hey,
Thanks for the prompt response!
I completely agree that biologically this is improbable to see. I do think this is a technical artifact, I just cannot wrap my head around the basis/metric on which to filter these cells out.
So here is an example:
This is a male sample. I ran scAbsolute with ploidy window min 1.2 and and max 2.9. I then subset cells with rpc > 10 and total counts >10,000 (the coverage of our method is lower than DLP+).
<img width="1440" alt="Screen Shot 2024-08-15 at 2 31 17 PM" src="https://github.com/user-attachments/assets/b62943f4-0e22-4c08-90e3-7eaf795157de">
Here are some examples of the per cell plots:
<img width="875" alt="Screen Shot 2024-08-15 at 2 34 47 PM" src="https://github.com/user-attachments/assets/c08cd839-866c-4765-acce-fbf17e5be81b">
<img width="873" alt="Screen Shot 2024-08-15 at 2 34 27 PM" src="https://github.com/user-attachments/assets/4f113847-7cd1-4a6c-850e-7d3c78124214">
<img width="868" alt="Screen Shot 2024-08-15 at 2 33 49 PM" src="https://github.com/user-attachments/assets/5024fb13-cfa1-433b-8182-0d5bc7c741a6">
<img width="870" alt="Screen Shot 2024-08-15 at 2 32 19 PM" src="https://github.com/user-attachments/assets/819606ab-d754-403d-b833-6070ef6bd465">
<img width="884" alt="Screen Shot 2024-08-15 at 2 44 27 PM" src="https://github.com/user-attachments/assets/145d4ee9-ebf1-4b8a-9289-4a9ddbb16512">
<img width="875" alt="Screen Shot 2024-08-15 at 2 34 47 PM" src="https://github.com/user-attachments/assets/b07ebec0-d30d-46f6-a4e1-195b6de34db8">
<img width="873" alt="Screen Shot 2024-08-15 at 2 34 27 PM" src="https://github.com/user-attachments/assets/22599af8-f498-4a60-bc41-da98ada78267">
<img width="868" alt="Screen Shot 2024-08-15 at 2 33 49 PM" src="https://github.com/user-attachments/assets/d44baf60-ed16-4e65-8d14-4601cc695b01">
<img width="871" alt="Screen Shot 2024-08-15 at 2 45 01 PM" src="https://github.com/user-attachments/assets/d0c251ab-4677-4b1c-b940-4fc4b41c3f54">
<img width="881" alt="Screen Shot 2024-08-15 at 2 45 28 PM" src="https://github.com/user-attachments/assets/9b6aebd2-8d33-4e7d-9409-dc76e6eaea3c">
<img width="869" alt="Screen Shot 2024-08-15 at 2 45 51 PM" src="https://github.com/user-attachments/assets/a75ee605-0586-4d4a-bc65-5353edc5b3b3">
<img width="868" alt="Screen Shot 2024-08-15 at 2 46 26 PM" src="https://github.com/user-attachments/assets/b04f82f4-2c00-4a6e-a311-d2a73e0aacc5">

I am also wondering about these other cells that show a lot of amplifications across the genome. This is also rather unexpected, however, this paper https://www.nature.com/articles/s41467-024-47664-z describes "monster cells" that they also observe in their sample. Wondering if its a technical artifact in my case as I also see this in my control..

**Comment by Urja25** [comment]
Also, the ploidy parameter you see on the heatmap is actually the "ploidy.mod" feature in the QDNAseq object which I realized does not represent the ploidy value, rather the average CNA across genome per cell if I am not mistaken. So please ignore that!

**Comment by leachim** [comment]
Okay, these are pretty typical things happening here. You have a mixture of a few things. Some of the cells are just cycling, either S-phase or G2 phase. You can partially address G2 by setting a wider ploidy window, at least to the 1.2-5.0 or something range, then it should correctly identify the ploidy for some of the G2. Not all of them, though, as it's pretty challenging to always get those right. My guess is cell plot 3 and 6 are examples of cells in G2.

**Comment by leachim** [comment]
Okay, so a few things here. I think first you should run the cell cycle classifier to exclude cycling cells (cells in S-phase). It should be fairly straightforward using the tutorials in this repo to do that. I think some of the cells are probably just cycling, by the looks of it. If you use a cell line this can be quite a large number of your cells (> 20%), see the manuscript for examples. And then some of the cells just look like the sequencing has failed, e.g. the very last picture and number 5. I don't think the methods are currently reliable enough to identify a single weird cell as a monster cell, it's much more likely it's just a sequencing/sample processing artefact. The waviness you see on the first plot is just GC content, I think there is an option to plot a corrected image with the plotCopynumber function in the package. The second manuscript scUnique has an integrated copy number caller that will give you better calls and deal with that better than scAbsolute, but it depends what you want to achieve with your analysis.

**Comment by leachim** [comment]
Also for the filtering I think I have one tutorial just for that, have a look at that for some inspiration. If you have very low coverage (rpc < 25 at 1MB resolution, but for that the ploidy estimate has to be correct, because rpc depends on the ploidy estimate), you could run the analysis for all cells with rpc > 25, identify the ploidy peaks and then rerun the analysis with very constrained ploidy estimates and potentially a more sensitive segmentation. That's a bit of a hack, but it might give you more cells to work with. Depends a bit on how many cells fall foul of the filter....

**Comment by leachim** [comment]
Oh, and I made a mistake, I meant male sample is easier with one X chromosome, because you have a step between X and the other chromosomes in normal samples. So might be worth keeping that in depending on whether you care more about accurate ploidy or accurate copy number calls on the X chromosome. I would not keep the Y chromosome in, it's just very unreliable and usually not too informative either.

**Comment by Urja25** [comment]
Hi Michael,

Thanks for all the useful feedback. As per our discussion, I re-ran scAbsolute for this sample with a ploidy window of **1.2 - 5.** I also excluded the Y chr from analysis, however, I did keep the X chr.
I excluded cells with used.reads < 10,000 and rpc < 25. Then, I estimated the cycling state of cells based on your vignette and excluded all cycling cells (these constituted about 9.5% of cells). The cut-off value was 1.0 and iqr was 1.5.

e.g. 
<img width="1149" alt="Screen Shot 2024-08-21 at 1 55 12 PM" src="https://github.com/user-attachments/assets/16859ba7-a01d-427a-bc7f-8d440b59d12d">

<img width="738" alt="Screen Shot 2024-08-21 at 1 50 16 PM" src="https://github.com/user-attachments/assets/000de425-71fe-4582-a677-c7af525f69ac">

I then plotted the heatmap and single cell plots that looked as follows:

[CopyOfLFS05CP_12_5_without_replicating_rpc25.pdf](https://github.com/user-attachments/files/16690876/CopyOfLFS05CP_12_5_without_replicating_rpc25.pdf)

<img width="866" alt="Screen Shot 2024-08-21 at 1 34 47 PM" src="https://github.com/user-attachments/assets/b48bbc4d-3fb2-4748-8c57-607dc2d5c618">
<img width="869" alt="Screen Shot 2024-08-21 at 1 35 03 PM" src="https://github.com/user-attachments/assets/69d7de22-f125-4ba9-9c7b-4dbb5ed49601">
<img width="867" alt="Screen Shot 2024-08-21 at 1 35 26 PM" src="https://github.com/user-attachments/assets/694f1db9-d1e4-4a44-aaff-3e7508c384be">
<img width="866" alt="Screen Shot 2024-08-21 at 1 35 44 PM" src="https://github.com/user-attachments/assets/fb48779b-cca6-411b-a082-a58617320850">
<img width="864" alt="Screen Shot 2024-08-21 at 1 36 02 PM" src="https://github.com/user-attachments/assets/26c3a2a6-24f6-4af1-a37f-7d5247dd6a94">
<img width="871" alt="Screen Shot 2024-08-21 at 1 36 20 PM" src="https://github.com/user-attachments/assets/f656bd4f-6a58-46bd-aafd-461c93647124">

(btw the gc correction for the single cell plots was true in the earlier plots and even these ones, yet it does not eliminate the so-called waviness).

Having noticed that there are still some cells that may have a ploidy < 2 or > 2, which could represent polyploid, or pseudiploid cells respectively, I set a ploidy threshold of 1.8-2 within this dataset such that I only retain "diploid" cells. This is obviously not a perfect method since the cells with ploidy >2 could represent cells of interest. However, I currently don't know how to distinguish G2 cells from pathologically polyploid cells. The heatmap and single cell plots are as follows:

[CopyOfLFS05CP_12_5_without_replicating_rpc25_ploidy2.pdf](https://github.com/user-attachments/files/16690885/CopyOfLFS05CP_12_5_without_replicating_rpc25_ploidy2.pdf)

<img width="866" alt="Screen Shot 2024-08-21 at 1 42 01 PM" src="https://github.com/user-attachments/assets/5afc4c63-3aa6-49ce-8456-89c09904f639">
<img width="869" alt="Screen Shot 2024-08-21 at 1 42 21 PM" src="https://github.com/user-attachments/assets/9c78c659-d5e9-4ef2-9120-c2a5943a42aa">
<img width="870" alt="Screen Shot 2024-08-21 at 1 42 39 PM" src="https://github.com/user-attachments/assets/01cfe684-1989-4020-a4b9-b394e2097833">
<img width="870" alt="Screen Shot 2024-08-21 at 1 43 06 PM" src="https://github.com/user-attachments/assets/56650f3b-29f4-4572-a4a3-b400956fa1de">
<img width="873" alt="Screen Shot 2024-08-21 at 1 43 19 PM" src="https://github.com/user-attachments/assets/2ae39a79-5964-4482-9a6a-2b137a7a0487">
<img width="870" alt="Screen Shot 2024-08-21 at 1 43 59 PM" src="https://github.com/user-attachments/assets/f5a40206-fd10-4f8c-ad8b-44e1ef2bba8c">
<img width="868" alt="Screen Shot 2024-08-21 at 1 44 25 PM" src="https://github.com/user-attachments/assets/c1249428-816f-4e34-be53-d60620a11716">
<img width="871" alt="Screen Shot 2024-08-21 at 1 44 50 PM" src="https://github.com/user-attachments/assets/a4fa2ec6-d484-43f1-be34-cafc5e0af751">
<img width="869" alt="Screen Shot 2024-08-21 at 1 45 19 PM" src="https://github.com/user-attachments/assets/4e286bfb-7bf2-4896-ade2-3a0dbacd0879">
<img width="875" alt="Screen Shot 2024-08-21 at 1 45 32 PM" src="https://github.com/user-attachments/assets/d8c05eb9-a974-47c9-b473-5db365bfc76b">
<img width="872" alt="Screen Shot 2024-08-21 at 1 45 50 PM" src="https://github.com/user-attachments/assets/5c250afc-33ed-4bf9-9a46-6708699d83fa">


As you can see there are still a couple of cells where sequencing has seemingly failed, and one observable pattern is that all points (reads) on X chr lie at 0. Yet, the segment is called at CN 1. I am wondering if there is a metric based on which I can filter these cells out. But in general, this is the only way I can eliminate "bad-looking" cells so far. I am wondering if this strategy is too stringent. I am also wondering if the estimation of cycling state is incorrect.

**Comment by leachim** [comment]
`Having noticed that there are still some cells that may have a ploidy < 2 or > 2, which could represent polyploid, or pseudiploid cells respectively, I set a ploidy threshold of 1.8-2 within this dataset such that I only retain "diploid" cells. This is obviously not a perfect method since the cells with ploidy >2 could represent cells of interest. However, I currently don't know how to distinguish G2 cells from pathologically polyploid cells. The heatmap and single cell plots are as follows:`

I think that's too strict. I would set it to median(ploidy) +- 0.5, otherwise you might exclude some perfectly fine cells.

**Comment by leachim** [comment]
But by the looks of it, you still have quite a lot of outliers.

**Comment by leachim** [comment]
You could try to make the cell cycle classifier a little bit stricter, but looking at the distribution that might mean excluding a fair number of good cells, too. Maybe try first to run the other qc methods (qc_gini and qc_mapd) that are described in the vignette. I have given you access to the scUnique part of the pipeline, if you run that, you should also get a better phylogeny. Unfortunately, you have to try a little bit with the thresholds, there is no good automatic way to fix the thresholds for good/bad cells.

**Comment by Urja25** [comment]
Thanks, I am going to attempt scUnique as well. For now, I am deleting my comments with heatmaps.

**Comment by leachim** [comment]
Okay, let me know how that goes. The output should be a bit more informative, especially as you can see whether the noisy cells have any sort of structure. Hard to see that in the other plots.

**Comment by Urja25** [comment]
Hi Michael. So I re-ran scAbsolute for another sample (min ploidy 1.2, max ploidy 5) without considering sex chromosomes (at 1000kb).
All cells passed with the first run of scAbsolute. I then ran the qc script, having changed the thresholds for gini and mapd arbitrarily (the ones used in the original qc script are too stringent for our scDNA method). Here is the code:

`## script for interactive QC analysis of scAbsolute output
# We recommend manually running and inspecting the results,
# while it's theoretically possible to run this script automated as well

# NOTE: by default, datasets are split by UID and SLX variable,
# so it is important to set these two variables in the df data frame
# we throw an error below if this hasn't happened

## Variables ####
args = commandArgs(trailingOnly=TRUE)
set.seed(2020)

if (interactive()){
  rm(list=ls())
  
  sampleFile = c(
    #"~/scDNAseq-workflow/results/500/PEO1_500.rds",
    #"~/scDNAseq-workflow/results/500/PEO4_500.rds"
    "/home/u855h/chromothripsis/urja/scDNAseq-workflow2/results/1000/LFS01CP_12_5_1000.rds",
    
  )
  sampleName = "LFS01CP_12_5"
  #sampleName = "PEO1-PEO4"
  
}else{
  sampleFile = args[1]
  sampleName = args[2]
}
sampleFile = do.call("c", (base::strsplit(sampleFile, split=",")))

## Setup ====
BASEDIR="~/"
BASEDIR=normalizePath(BASEDIR)
WORKFLOW_PATH="~/chromothripsis/urja/scDNAseq-workflow2/"
require(QDNAseq, quietly = TRUE, warn.conflicts = FALSE)
require(ggbeeswarm, quietly = TRUE, warn.conflicts = FALSE)
require(ggpubr, quietly = TRUE, warn.conflicts = FALSE)
require(tidyverse, quietly = TRUE, warn.conflicts = FALSE)
require(ComplexHeatmap, quietly = TRUE, warn.conflicts = FALSE)
source(file.path(BASEDIR, "scUnique/R/core.R"))
source(file.path(BASEDIR, "scUnique/R/visualize.R"))
source(file.path(BASEDIR, "scAbsolute/R/core.R"))
source(file.path(BASEDIR, "scAbsolute/R/visualization.R"))


LFS01CP_12_5 <- readRDS("/home/u855h/chromothripsis/urja/scDNAseq-workflow2/results/1000/LFS01CP_12_5_1000.rds")

# Check for basic properties - here we use the common name format to directly create UID/SLX from filenames
df = Biobase::pData(LFS01CP_12_5)
df
df <- df %>%
  dplyr::mutate(UID = "LFS01CP", SLX = "LFS01CP")

# 1. number of reads extreme outliers
reads_cutoff = quantile(df$used.reads, c(0.025, 0.975)) # by default we remove the top and bottom 2.5% of cells with very high or low read number 
p_coverage = ggplot(data=df %>% dplyr::select(rpc, used.reads, UID, SLX)) +
  geom_histogram(aes(x=used.reads, y=..density.., color=interaction(UID, SLX)), bins = 100, position="identity", fill="white") +
  geom_density(aes(x=used.reads, color=interaction(UID, SLX))) +
  geom_vline(xintercept = reads_cutoff, color="red") +
  theme_pubclean()
issue_coverage = colnames(LFS01CP_12_5)[(Biobase::pData(LFS01CP_12_5)[["used.reads"]] < reads_cutoff[[1]]) | 
                                    (Biobase::pData(LFS01CP_12_5)[["used.reads"]] > reads_cutoff[[2]])]
p_coverage
if(any(Biobase::pData(LFS01CP_12_5)[["rpc"]] < 25)){
  warning("Some cells have an rpc values of < 25!\nThis might indicate that you are under powered to detect rCNAs and copy number alterations at this bin size.")
  print(Biobase::pData(LFS01CP_12_5)[["name"]][Biobase::pData(LFS01CP_12_5)[["rpc"]] < 25]) 
}

# manually add cells that should be excluded
issue_manual = c()
exclude_cells = base::union(issue_coverage, issue_manual)
stopifnot(all(is.character(exclude_cells)))
include = setdiff(colnames(LFS01CP_12_5), exclude_cells)

LFS01CP_12_5 = LFS01CP_12_5[, include]
df = df %>% dplyr::filter(!(name %in% base::union(issue_coverage, issue_manual)))
stopifnot(dim(df)[[1]] == dim(LFS01CP_12_5)[[2]])
print(paste0("ISSUES: ", base::union(issue_coverage, issue_manual)))

df
df$mapd
summary(df$mapd)
df$gini_normalized
summary(df$gini_normalized)

df <- df %>% dplyr::filter(!is.na(gini_normalized))

# PARAMETERS ====
# see source for description
# replicating
cutoff_replicating = 1.0
cutoff_replicating_iqr = 1.5
cutoff_replicating_hard = NULL
# MAPD
mapd_cutoff = 0.1
mapd_density_control = FALSE
# Gini
gini_norm_cutoff = 0.2
gini_density_control = FALSE
# alpha
alpha_cutoff = 1.5
alpha_hard_cutoff = 0.05 # 0.05: about 99 percentile of data for 500 kb
print(paste0("Number of cells: ", dim(LFS01CP_12_5)[[2]]))

## Identify replicating and outlier cells ====


# 2. S phase cells
df = predict_replicating(df %>%
                           dplyr::mutate(UID2 = UID, SLX2=SLX),
                         cutoff_value=cutoff_replicating, iqr_value = cutoff_replicating_iqr, hard_threshold = cutoff_replicating_hard)
fig_cellcycle = ggplot(data = df) +
  geom_quasirandom(aes(x=SLX, y=cycling_activity, color=replicating, name=name), size=0.8, alpha=1.0) +
  geom_hline(aes(yintercept=cycling_cutoff_sd)) +
  geom_hline(aes(yintercept=cycling_median), linetype="dashed") +
  facet_wrap(~UID, scales = "free_x") + theme_pubclean()
fig_cellcycle

issue_sphase = df$name[df$replicating]

df$cycling = df$name %in% issue_sphase
table(df$cycling)
prop.table(table(df$cycling, df$UID), margin = 2)

# 3. QC control (after removal of cycling cells)
iq = qc_alpha(
              qc_gini_norm(
                            qc_mapd(df %>% dplyr::filter(!replicating), 
                            cutoff_value = mapd_cutoff, densityControl=mapd_density_control),
              cutoff_value = gini_norm_cutoff, densityControl = gini_density_control),
    cutoff_value=alpha_cutoff, hard_cutoff = alpha_hard_cutoff)
iq$outlier = iq$dmapd.outlier | iq$dgini.outlier | iq$alpha.outlier
aq = dplyr::left_join(df, iq, by="name", suffix=c("", ".y")) %>% dplyr::mutate(outlier = case_when(
                                              replicating ~ "replicating",
                                              name %in% iq$name[iq$outlier] ~ "outlier",
                                              TRUE ~ "pass"))

alpha_value = 0.7
scale_values = c(alpha_value, 0.1, alpha_value, alpha_value)
q1 = ggplot(data = aq) + geom_point(aes(x=rpc, y=dmapd, color=outlier, name=name, alpha=outlier)) + facet_wrap(~UID+SLX, scales = "free_y", nrow=1) + theme_pubclean() + scale_alpha_manual(values = scale_values)
q2 = ggplot(data = aq) + geom_point(aes(x=rpc, y=dgini, color=outlier, name=name, alpha=outlier)) + facet_wrap(~UID+SLX, scales = "free_y", nrow=1) + theme_pubclean() + scale_alpha_manual(values = scale_values)
q4 = ggplot(data = aq) + geom_point(aes(x=rpc, y=n_segs, color=outlier, name=name, alpha=outlier)) + facet_wrap(~UID+SLX, scales = "free_y", nrow=1) + theme_pubclean() + scale_alpha_manual(values = scale_values) 
q5 = ggplot(data = aq) + geom_quasirandom(aes(x=NA, y=error_seg_l2, color=outlier, name=name, alpha=outlier)) + facet_wrap(~UID+SLX, scales = "free_y", nrow=1) + theme_pubclean() + scale_alpha_manual(values = scale_values)
p3 = ggplot(data = aq %>% dplyr::filter(!replicating, rpc > 15)) + geom_quasirandom(aes(x=alpha.outlier, y=hmm.alpha, color=dmapd.outlier | dgini.outlier, name=name, alpha=outlier)) + geom_hline(yintercept=alpha_hard_cutoff, color="red", linetype="dashed") + facet_wrap(~UID+SLX, nrow=1) + theme_pubclean() + scale_alpha_manual(values = c(alpha_value, 0.1, alpha_value, 0.9, 1.0, 1.0)) + scale_y_continuous(trans="log10")

fig_qc = ggpubr::ggarrange(
  ggpubr::ggarrange(q1  + theme(legend.position = "none") + rremove("xlab"), #, strip.background = element_blank(), strip.text = element_blank()),
                    q2  + theme(legend.position = "none", strip.background = element_blank(), strip.text = element_blank()) + rremove("xlab"),
                    q4  + theme(legend.position = "none", strip.background = element_blank(), strip.text = element_blank()) + rremove("xlab"),
                    q5 + theme(legend.position = "right", strip.background = element_blank(), strip.text = element_blank()) + rremove("xlab") + 
                      guides(colour = guide_legend(nrow=1, override.aes = list(alpha = 1, size=2))) + 
                      theme(legend.key = element_rect(fill = "white"),
                            legend.title = element_text(size = 8, face = 2))
                    , ncol=2, nrow=2),
  p3,
  ncol=1, heights = c(2, 1))
fig_qc 
issue_qc = iq$name[iq$outlier]
df$remove = df$name %in% c(issue_qc)
table(df$remove)
prop.table(table(df$remove, df$UID), margin = 2)

# 4. Ploidy (cells with known wrong ploidy can be removed)
# consider re-running scAbsolute with better or more specific
# ploidy constraints if at all possible
p_ploidy = ggplot(data = aq) +
  geom_density2d(aes(x=rpc, y=ploidy), color="black") + 
  geom_point(aes(x=rpc, y=ploidy, color=outlier, name=name)) + theme_pubclean() + scale_alpha_manual(values = scale_values)
p_ploidy2 = ggplot(data = aq %>% dplyr::filter(rpc > 25)) + geom_density(aes(x=ploidy, color=outlier)) + theme_pubclean() # + facet_wrap(~UID)
p_ploidy2_low = ggplot(data = aq %>% dplyr::filter(rpc < 25)) + geom_density(aes(x=ploidy, color=outlier)) + theme_pubclean() 
p_reads = ggplot(data = aq) + geom_quasirandom(aes(x=interaction(UID, SLX), y=rpc, color=outlier, name=name, alpha=outlier)) + theme_pubclean() + scale_alpha_manual(values = scale_values) + geom_hline(yintercept=25, color="red", linetype="dashed") + theme(axis.text.x = element_text(angle=270))
fig_ploidy = ggpubr::ggarrange(p_ploidy, ggpubr::ggarrange(p_ploidy2, p_ploidy2_low, nrow=2), p_reads + theme(legend.position = "none"), nrow=1)
fig_ploidy

issue_ploidy = base::union(iq$name[iq$ploidy < 1.1], iq$name[iq$ploidy > 8.0])


## Optionally visualize copy number profiles
names = colnames(object)
pass_names = names[!(names %in% c(issue_sphase, issue_qc, issue_ploidy))]
issues = unique(base::union(base::union(issue_sphase, issue_qc), issue_ploidy))
names = c(pass_names, issues)
stopifnot(length(setdiff(names, colnames(object))) == 0)
ha = rowAnnotation(replicating = ifelse(names %in% issue_sphase, "TRUE", "FALSE"),
                   quality = ifelse(names %in% issue_qc, "TRUE", "FALSE"),
                   ploidy = ifelse(names %in% issue_ploidy, "TRUE", "FALSE"),
                   remove = ifelse(names %in% c(issue_sphase, issue_qc, issue_ploidy), "FALSE", "TRUE"),
                   col = list(replicating = c("FALSE" = "#63ACBE", "TRUE" = "#EE442F"),
                              quality = c("FALSE" = "#63ACBE", "TRUE" = "#EE442F"),
                              ploidy = c("FALSE" = "#63ACBE", "TRUE" = "#EE442F"),
                              remove = c("TRUE" = "#63ACBE", "FALSE" = "#EE442F")),
                   show_legend = c(FALSE, FALSE, FALSE, TRUE))

# optionally, plot raw copy number profiles
#fig_cn = plotCopynumberHeatmap(object[, names], cluster_rows = FALSE, har = ha)
#fig_cn


## select profiles to keep for scUnique analysis
df$keep = !(df$name %in% base::union(base::union(issue_qc, issue_sphase), issue_ploidy))
print("Total kept")
print(prop.table(table(df$keep, df$UID), margin=2))
print(table(df$keep, df$UID))

stopifnot(all(df$rpc[df$keep] > 0 & df$alpha[df$keep] > 0))
stopifnot(all(df$hmm.alpha[df$keep] > 0))
stopifnot(all(!is.na(df$hmm.alpha[df$keep]) & !is.nan(df$hmm.alpha[df$keep])))

ggplot(data = df %>% dplyr::filter(keep)) + geom_histogram(aes(x=ploidy), bins=50) + facet_wrap(~UID+SLX)

## export names of files that pass QC processing to file
print("Writing to file.")
ifelse(!dir.exists(file.path(WORKFLOW_PATH, "results/pass_qc/")), dir.create(file.path(WORKFLOW_PATH, "results/pass_qc/")), FALSE)
readr::write_tsv(df %>% dplyr::filter(keep) %>% dplyr::arrange(name) %>% dplyr::select(UID, SLX, name),
                 file=paste0(WORKFLOW_PATH, "results/pass_qc/pass_", sampleName, ".tsv"), append = FALSE, col_names=FALSE)`
                 
where:
> summary(df$mapd)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.07655 0.20317 0.29992 0.30909 0.40495 0.58653 
> summary(df$gini_normalized)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
0.06329 0.12960 0.18764 0.18809 0.24773 0.54297      17 

> table(df$cycling)

FALSE  TRUE 
 5414  1553 
> prop.table(table(df$cycling, df$UID), margin = 2)
       
         LFS01CP
  FALSE 0.777092
  TRUE  0.222908
  
  > table(df$remove)

FALSE  TRUE 
 3028  3939
 
 > print(prop.table(table(df$keep, df$UID), margin=2))
       
          LFS01CP
  FALSE 0.7882876
  TRUE  0.2117124

> print(table(df$keep, df$UID))
       
        LFS01CP
  FALSE    5492
  TRUE     1475
                 
![image](https://github.com/user-attachments/assets/27629356-4036-4acd-a457-5c28c540b915)

![image](https://github.com/user-attachments/assets/64b61253-4953-4e2d-ac92-3519b1050249)

![image](https://github.com/user-attachments/assets/e2188f5a-1920-4573-a2d4-fcd937479217)

![image](https://github.com/user-attachments/assets/8d1dbfa4-2321-4592-8111-067b87134e7d)

![image](https://github.com/user-attachments/assets/a837fb65-9280-461d-8c05-04de89d8c515)

I am now running scUnique for this sample. In the mean time, could you help me make sense of the QC I am observing?

Thanks a ton!

**Comment by leachim** [comment]
Looking at your ploidy plot, it doesn't seem correct to put the max ploidy cutoff at 5. I'd keep it at 8 and see how that changes things for the right part of the distribution. It's a bit surprising that you don't see any peak for the non-diploid population, but I would need to know more about the biology of the cells to make sense of it. 
More generally, you need to be fine with the QC part before you progress to running scUnique, since it should use only the cells that passed the QC analysis. Otherwise you can't trust the results. 
Most important, I'd recommend to split up the QC into two parts. Separate the cell populations based on ploidy and run it separately for the diploid and non-diploid cells, e.g. cells with ploidy > 3 based on your last plot. This way, the QC plots should look much better. The issue you observe stems from the fact that you mix two very different cell populations and you have many more diploid cells, so the fitting isn't right. 
redo the analysis with this split and the standard parameters and see if it makes more sense. 
Actually, may I use the last plot to add a point to the FAQ about this? It seems like an obvious issue people might run into.

**Comment by Urja25** [comment]
Is it possible to email you regarding the biology of the samples? I would like to have this information protected. I cannot seem to find your email address.

**Comment by leachim** [comment]
You can just find my email on this page, if you look for the first author on the scAbsolute paper. 
https://bsse.ethz.ch/cbg/group/people.html#s
