### ISSUE TITLE
scRNAseq data?

### ISSUE THREAD

**Issue by sunliang3361** [markowetzlab/scDNAseq-workflow#5]
Can we use your tool to analyze scRNAseq data? Thanks

**Comment by TBradley27** [comment]
Hello,

I am not the repo manager, but to help you with this, I think this question was answered in the related scAbsolute repository:

https://github.com/markowetzlab/scAbsolute/issues/3

**Comment by leachim** [comment]
I am afraid you can only use this tool with scDNAseq data. It's not applicable to scRNAseq data.
