### ISSUE TITLE
How do I run the snakemake for mm10 genome?

### ISSUE THREAD

**Issue by Urja25** [markowetzlab/scDNAseq-workflow#6]
Hi,

I am trying to figure out how to use the snakemake for mouse data? Any hints on which file I must change?

Best,
Urja

**Comment by AustinReed-1** [comment]
Hi @Urja25,

Thanks for your interest! 

I have just made a couple changes on the 6-snakemake-for-mm10-genome branch and you should be able to run your mouse data easily now. You only needing to specify the species and genome inputs of the config.yaml file as "Mouse" and "GRCm38" and run as the README file instructs over your mice samples!

Hopefully that helps,
Austin
