### ISSUE TITLE
Unresolved merge conflicts in the default/main branch

### ISSUE THREAD

**Issue by TBradley27** [markowetzlab/scDNAseq-workflow#9]
Hello,

There seems to be unresolved merging issues in the following files:

workflow/rules/combine.smk
workflow/rules/density.smk
workflow/rules/qc.smk
workflow/rules/scale_scAbsolute.smk

This prevents the workflow from running correctly

**Comment by leachim** [comment]
@shafighi if you could please commit your changes asap

**Comment by shafighi** [comment]
It should be fine now.

**Comment by leachim** [comment]
@TBradley27 please give it a try now and let us know if it's still not working.

**Comment by TBradley27** [comment]
Thanks - the merging issues seem to have been resolved.

However, the output path of the rule _scale_scAbsolute_ does not match the input path of the rule _combine_ - as one rule uses the 'scale' subdirectory, whilst the other does not

**Comment by leachim** [comment]
@shafighi please have a look at this, should be a very quick fix.

**Comment by shafighi** [comment]
It should be fixed now. @TBradley27 please let us know if it is still not working.
